# bechmark general settings
benchmark:
    # specify dataset download link and prompt for each tasks
    tasks:
        kie:
            dataset:
            prompt:
        ocr:
            dataset:
            prompt:
        vqa:
            dataset:
            prompt:

    # select which model to use for performance testing
    tools:
        AutoModelForVision2Seq:
            - smolvlm
        AutoModelForImageTextToText:
            - 
        VisionEncoderDecoderModel:

# hyperparameters for vlm-models
vlm-models:
    smolvlm:
        top_p:
        top_k:
        max_tokens:
    qwen2.5-vl:
        top_p:
        top_k:
        max_tokens:
    gemma3n:
        top_p:
        top_k:
        max_tokens:
    dolphin:
        top_p:
        top_k:
        max_tokens:
    nanonets_ocr_s:
        top_p:
        top_k:
        max_tokens:
