hugginface:
    smolvlm:
        model: HuggingFaceTB/SmolVLM2-500M-Video-Instruct
        temperature:
        top_p:
        top_k:
        repetition_penalty:
        max_new_tokens:

    qwen2.5-vl:
        model:

ollama:
    qwen2.5-vl:
        model: qwen2.5vl:3b