SmolVLM:
    model_id: HuggingFaceTB/SmolVLM-Instruct
    type: Vision2Seq
    parameters:
        max_new_tokens:
        repetition_penalty:
        temperature:
        top_k:
        top_p:

SmolVLM2:
    model_id: HuggingFaceTB/SmolVLM2-2.2B-Instruct
    type: ImageTextToText
    parameters:
        max_new_tokens:
        repetition_penalty:
        temperature:
        top_k:
        top_p:

Qwen2.5-VL:
    model_id: Qwen/Qwen2.5-VL-3B-Instruct
    type: Qwen2_5_VL
    parameters:
        max_new_tokens:
        repetition_penalty:
        temperature:
        top_k:
        top_p:

Gemma3n:
    model_id: google/gemma-3n-e4b-it
    type: Gemma3n
    parameters:
        max_new_tokens:
        repetition_penalty:
        temperature:
        top_k:
        top_p:

Nanonets-OCR-s:
    model_id: nanonets/Nanonets-OCR-s
    type: ImageTextToText
    parameters:
        max_new_tokens:
        repetition_penalty:
        temperature:
        top_k:
        top_p: