tests:
    dataset: ""
    models: 
        - SmolVLM
        - Qwen2.5-VL
        - Gemma3n


kie:
    datasets:
        -
        - 
    system_prompt:
    user_prompt:

classification:
    datasets:
        - 
        -
    system_prompt:
    user_prompt: