test:
    task: kie
    dataset: sroie
    models: 
        - SmolVLM
        - Qwen2.5-VL
        - Gemma3n


tasks:
    kie:
        datasets:
            -
            - 
        system_prompt:
        user_prompt:

    classification:
        datasets:
            - 
            -
        system_prompt:
        user_prompt: