test:
    task: kie
    dataset: sroie
    models: 
        - SmolVLM
        - Qwen2.5-VL
        - Gemma3n


tasks:
    kie:
        system_prompt:
        user_prompt:

    cls:
        system_prompt:
        user_prompt:

    vqa:
        system_prompt:
        user_prompt:
    
    obj:
        system_prompt:
        user_prompt:

    ocr:
        system_prompt:
        user_prompt: