test:
    task: kie
    dataset: sroie
    models: 
        - SmolVLM
        - Qwen2.5-VL
        - Gemma3n


tasks:
    kie:
        system_prompt:
        user_prompt:

    classification:
        system_prompt:
        user_prompt: