SmolVLM-500M:
    model_id: HuggingFaceTB/SmolVLM-500M-Instruct
    type: Vision2Seq
    parameters:
        max_new_tokens: 1000
        repetition_penalty: 1.3
        temperature: 0.5
        top_k: 2
        top_p: 0.9
    quantization:

SmolVLM:
    model_id: HuggingFaceTB/SmolVLM-Instruct
    type: Vision2Seq
    parameters:
        max_new_tokens: 1000
        repetition_penalty: 1.3
        temperature: 0.7
        top_k: 10
        top_p: 0.9

SmolVLM2:
    model_id: HuggingFaceTB/SmolVLM2-2.2B-Instruct
    type: ImageTextToText
    parameters:
        max_new_tokens: 1000
        repetition_penalty: 1.3
        temperature: 0.7
        top_k: 10
        top_p: 0.9

Qwen2.5-VL-3B:
    model_id: Qwen/Qwen2.5-VL-3B-Instruct
    type: Qwen2.5-VL
    parameters:
        max_new_tokens: 1000
        repetition_penalty:
        temperature:
        top_k:
        top_p:
    quantization:
        load_in_8bit: True

Qwen2.5-VL-7B:
    model_id: Qwen/Qwen2.5-VL-7B-Instruct
    type: Qwen2.5-VL
    parameters:
        max_new_tokens: 1000
        repetition_penalty:
        temperature:
        top_k:
        top_p:
    quantization:
        load_in_8bit: True

Gemma3n:
    model_id: unsloth/gemma-3n-E4B-it-GGUF
    type: Gemma3n
    parameters:
        max_new_tokens: 1000
        repetition_penalty:
        temperature:
        top_k:
        top_p:

Nanonets-OCR-s:
    model_id: nanonets/Nanonets-OCR-s
    type: ImageTextToText
    parameters:
        max_new_tokens:
        repetition_penalty:
        temperature:
        top_k:
        top_p: