SmolVLM:
    model_id: HuggingFaceTB/SmolVLM-500M-Instruct
    type: Vision2Seq
    parameters:
        max_new_tokens:
        repetition_penalty:
        temperature: 0.7
        top_k: 2
        top_p: 0.6
    quantization:

SmolVLM2:
    model_id: HuggingFaceTB/SmolVLM2-2.2B-Instruct
    type: ImageTextToText
    parameters:
        max_new_tokens: 1000
        repetition_penalty: 1.3
        temperature:
        top_k:
        top_p: 0.9

Qwen2.5-VL:
    model_id: unsloth/Qwen2.5-VL-3B-Instruct-unsloth-bnb-4bit
    type: Qwen2.5-VL
    parameters:
        max_new_tokens:
        repetition_penalty:
        temperature:
        top_k:
        top_p:

Gemma3n:
    model_id: unsloth/gemma-3n-E4B-it-GGUF
    type: Gemma3n
    parameters:
        max_new_tokens:
        repetition_penalty: 1.0
        temperature:
        top_k: 64
        top_p: 0.95

Nanonets-OCR-s:
    model_id: nanonets/Nanonets-OCR-s
    type: ImageTextToText
    parameters:
        max_new_tokens:
        repetition_penalty:
        temperature:
        top_k:
        top_p: